# Generated by Django 3.1.3 on 2020-11-21 08:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Loginform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
            managers=[
                ('persons', django.db.models.manager.Manager()),
            ],
        ),
    ]
