# Generated by Django 3.1.3 on 2020-11-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loginform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_quentity', models.CharField(max_length=100)),
                ('Item_Price', models.IntegerField()),
                ('Invoice_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loginform.invoiceheader')),
            ],
        ),
    ]
