# Generated by Django 3.1.3 on 2020-11-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('CountryName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CurrencyValue', models.IntegerField()),
            ],
        ),
    ]
