# Generated by Django 3.1.3 on 2020-11-21 08:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Loginform', '0002_person_details'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person_details',
            managers=[
                ('personorder', django.db.models.manager.Manager()),
            ],
        ),
    ]
